package com.cvrce.apraisal.enums;

public enum AppraisalStatus {
    DRAFT,
    SUBMITTED,
    DEPARTMENT_REVIEW,
    REUPLOAD_REQUIRED,
    HOD_APPROVED,
    COLLEGE_REVIEW,
    CHAIR_REVIEW,
    COMPLETED,
    PENDING_VERIFICATION,
    RETURNED_TO_HOD,
    RETURNED_TO_CHAIRPERSON,
    PENDING_PRINCIPAL_APPROVAL
}
